### ISSUE TITLE
Cannot install the project

### ISSUE THREAD

**Issue by whuissyxa** [osu-crypto/SpOT-PSI#1]
Hello! I install the project follow your steps and build frontend.exe. However, when I run ./bin/frontend.exe -t, it shows Segmentation fault (core dumped).
![图片1](https://user-images.githubusercontent.com/36789261/71388305-c5625e80-2632-11ea-8d3a-418c5cf932a0.png)
   When I bash all.get in ./thirdparty/linux, some red errors about gmp happened as follows:
![image](https://user-images.githubusercontent.com/36789261/71388394-196d4300-2633-11ea-9121-8fca3e2f5562.png)
   Could you give me some advice on it? Thanks a lot!

**Comment by nitrieu** [comment]
the second pic shows that m4 hasn't installed. Please try 
`sudo apt-get update`
`sudo apt-get install m4`

**Comment by whuissyxa** [comment]
Thank you very much for your reply and guidance! I‘ll try it soon.

**Comment by whuissyxa** [comment]
Sorry, I installed m4, but get the same error:
![image](https://user-images.githubusercontent.com/36789261/71391793-9f43bb00-2640-11ea-8dac-e8287753920b.png)
When I bash all.get in libOTe/cryptoTools/thirdparty/linux$ after installing m4, it shows:
![image](https://user-images.githubusercontent.com/36789261/71391892-ffd2f800-2640-11ea-8365-236237e27d9b.png)
![image](https://user-images.githubusercontent.com/36789261/71392117-e54d4e80-2641-11ea-9874-49f3a95fcc06.png)
When I bash all.get in SpOT-PSI/thirdparty/linux, it showed
![image](https://user-images.githubusercontent.com/36789261/71392338-9b189d00-2642-11ea-8b71-9d96591e8a7a.png)
![image](https://user-images.githubusercontent.com/36789261/71392342-a23fab00-2642-11ea-8dab-3b5024998c83.png)
![image](https://user-images.githubusercontent.com/36789261/71392356-a9ff4f80-2642-11ea-8ced-507f28fe6943.png)
![image](https://user-images.githubusercontent.com/36789261/71392376-bb485c00-2642-11ea-9c71-8b44e96c6172.png)
![image](https://user-images.githubusercontent.com/36789261/71392442-019dbb00-2643-11ea-977e-7e474a5eb243.png)
![image](https://user-images.githubusercontent.com/36789261/71392461-0febd700-2643-11ea-9f8e-4a5eaa1839e3.png)
![image](https://user-images.githubusercontent.com/36789261/71392507-390c6780-2643-11ea-84cb-72c07b668354.png)
Does these results normal? Thanks a lot for your spending time and advice!

**Comment by nitrieu** [comment]
Yes, you can try the below command for more result 
`./bin/frontend.exe -r 1 -n 8 -t 1 -p 0 -ip 172.31.77.224:1212 & ./bin/frontend.exe -r 0 -n 8 -t 1 -p 0 -ip 172.31.77.224:1212`
