### ISSUE TITLE
 Cannot assign requested address

### ISSUE THREAD

**Issue by whuissyxa** [osu-crypto/SpOT-PSI#2]
Hi Ni Trieu! Thank you for sharing the open source project!
   I install the project twice as your instructions in different environment, but both get the same result:
![图片](https://user-images.githubusercontent.com/36789261/71815708-54ec2080-30bb-11ea-95c2-ada625c21170.png)
   Could you please give me some advice on it? Thank you very much!

**Comment by nitrieu** [comment]
Thanks for sharing. Can you try it with localhost to see whether the code works, and then try other IP address. You might htop to see whether you executed this code before, or try ping, to make sure that these IP addresses are available.
