### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MingliWu** [osu-crypto/SpOT-PSI#3]
When testing by "./bin/frontend.exe -t",  it shows "Segmentation fault (core dumped)" even when I run the code on a server with 119GB RAM.

**Comment by nitrieu** [comment]
thanks. fixed. 
![image](https://user-images.githubusercontent.com/16380791/95023570-a61d4680-0632-11eb-964c-548ba197c5cd.png)
